const { test, expect, request } = require('@playwright/test')

test('Verify Events Navigation', async ({ browser }) => {
    const context = await browser.newContext()
    const page = await context.newPage()
    await page.goto('https://eventhub.rahulshettyacademy.com/login')
    await page.getByPlaceholder('you@email.com').fill('jayant.prasad.9920@gmail.com')
    await page.locator('#password').fill('Hanumanji@1990')
    await page.locator('#login-btn').click()
    await page.waitForLoadState('networkidle')
    await page.locator('#nav-events').click()
    await page.waitForLoadState('networkidle')
    const labelName = await page.locator('.mb-8 h1').textContent()
    await expect(labelName).toBe("Upcoming Events")
    await context.close()
});
test('Verify Event page and its webelements',async({browser})=>{
const context = await browser.newContext()
    const page = await context.newPage()
    await page.goto('https://eventhub.rahulshettyacademy.com/login')
    await page.getByPlaceholder('you@email.com').fill('jayant.prasad.9920@gmail.com')
    await page.locator('#password').fill('Hanumanji@1990')
    await page.locator('#login-btn').click()
    await page.waitForLoadState('networkidle')
    await page.locator('#nav-events').click()
    await page.waitForLoadState('networkidle')
    expect(await page.getByPlaceholder("Search events, venues…")).toBeVisible()
    expect(await page.locator('.cursor-pointer').first()).toBeVisible()
    expect(await page.locator('.cursor-pointer').last()).toBeVisible()
    expect(await page.getByRole('button',{name:'Add New Event'})).toBeVisible()
    await context.close()
})
test('Validate Add Event validations functionality',async({browser})=>{
    const context = await browser.newContext()
    const page = await context.newPage()
    await page.goto('https://eventhub.rahulshettyacademy.com/login')
    await page.getByPlaceholder('you@email.com').fill('jayant.prasad.9920@gmail.com')
    await page.locator('#password').fill('Hanumanji@1990')
    await page.locator('#login-btn').click()
    await page.waitForLoadState('networkidle')
    await page.locator('#nav-events').click()
    await page.waitForLoadState('networkidle')
    await page.getByRole('button',{name:'Add New Event'}).click()
    await page.waitForLoadState('networkidle')
    await page.getByRole('button',{name:'+ Add Event'}).click()
    await page.getByText("Title is required")
    await page.getByText("City is required")
    await page.getByText("Venue is required")
    await page.getByText("Event date is required")
    await page.getByText("Enter a valid price (≥ 0)")
    await page.getByText("Must have at least 1 seat")
    await context.close()
})
