const { test, expect } = require('@playwright/test')
const jsonTD= JSON.parse(JSON.stringify(require('../Utils/MyBookingTD.json')))

test('My Booking navigation and validate clear booking and click', async ({ browser }) => {
    const context = await browser.newContext()
    const page = await context.newPage()
    await page.goto('https://eventhub.rahulshettyacademy.com/login')
    await page.getByPlaceholder('you@email.com').fill('jayant.prasad.9920@gmail.com')
    await page.locator('#password').fill('Hanumanji@1990')
    await page.locator('#login-btn').click()
    await page.waitForLoadState('networkidle')
    await page.locator('#nav-bookings').click()
    expect(await page.getByRole('button', { name: 'Clear all bookings' })).toBeVisible()
    await page.waitForLoadState('networkidle')
    await page.on('dialog', dialog => dialog.accept())
    await page.getByRole('button', { name: 'Clear all bookings' }).click()
})
test('Navigate my bookings and search bookings', async ({ browser }) => {
    const context = await browser.newContext()
    const page = await context.newPage()
    await page.goto('https://eventhub.rahulshettyacademy.com/login')
    await page.getByPlaceholder('you@email.com').fill('jayant.prasad.9920@gmail.com')
    await page.locator('#password').fill('Hanumanji@1990')
    await page.locator('#login-btn').click()
    await page.waitForLoadState('networkidle')
    await page.locator('#nav-bookings').click()
    await page.getByRole('button', { name: 'Browse Events' })
    await page.getByRole('button', { name: 'Browse Events' }).click()
    await page.locator('.cursor-pointer').nth(1).selectOption('Pune')
    await expect(page.locator('.text-lg').nth(1)).toBeVisible()
    await page.getByRole('button', { name: 'Clear filters' }).click()
    await page.getByPlaceholder('Search events, venues…').fill('Dilli Diwali Mela')
    const date = await page.locator('.line-clamp-1').nth(0).textContent()
    await expect(date).toBe('Tue, 20 Oct')
    await expect(page.locator('.line-clamp-1').nth(1)).toBeVisible()
    await page.waitForLoadState('networkidle')
    await expect(page.locator('#book-now-btn').first()).toBeVisible()

})
test('Create My booking', async ({ browser }) => {
    const context = await browser.newContext()
    const page = await context.newPage()
    await page.goto('https://eventhub.rahulshettyacademy.com/login')
    await page.getByPlaceholder('you@email.com').fill('jayant.prasad.9920@gmail.com')
    await page.locator('#password').fill('Hanumanji@1990')
    await page.locator('#login-btn').click()
    await page.waitForLoadState('networkidle')
    await page.locator('#nav-bookings').click()
    await page.waitForLoadState('networkidle')
    await page.getByRole('button', { name: 'Browse Events' }).click()
    await page.locator('#book-now-btn').first().click()
    //validate confirm booking
    await page.locator('#confirm-booking').click()
    await page.getByText('Name must be at least 2 chars')
    await page.getByText('Enter a valid email')
    await page.getByText('Enter a valid 10-digit phone')
    await page.locator('#customerName').fill("Jayant Prasad")
    await page.locator('#customer-email').fill("jayant.prasad.9920@gmail.com")
    await page.locator('#phone').fill("9874820677")
    await page.locator('#confirm-booking').click()
    await page.getByText('Booking Confirmed! 🎉')
})
test('Cancel Booking', async ({ browser }) => {
    const context = await browser.newContext()
    const page = await context.newPage()
    await page.goto(jsonTD.url)
    await page.getByPlaceholder('you@email.com').fill(jsonTD.emailId)
    await page.locator('#password').fill(jsonTD.password)
    await page.locator('#login-btn').click()
    await page.waitForLoadState('networkidle')
    await page.locator('#nav-bookings').click()
    await page.waitForLoadState('networkidle')
    await page.locator('#cancel-booking-btn').click()
    await page.locator('#confirm-dialog-yes').click()
    
})